; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n8r8]
platform = espressif32 @ ^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.psram = enable
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=3
	-std=gnu++17
lib_deps = 
	nanopb/Nanopb @ ^0.4.7
	adafruit/Adafruit BNO08x @ ^1.2.5
	https://github.com/sparkfun/SparkFun_TMAG5273_Arduino_Library.git
	adafruit/Adafruit BusIO @ ^1.14.1
	h2zero/NimBLE-Arduino @ ^1.4.1
	links2004/WebSockets @ ^2.4.1
	Wire
	7semi-solutions/7Semi_TMAG5273@^1.0.0
