/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_GLOVE_DATA_PB_H_INCLUDED
#define PB_GLOVE_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current nanopb-generator.
#endif

/* Struct definitions */
typedef struct _GloveData {
    uint32_t timestamp;
    pb_size_t hall_features_count;
    float hall_features[15];
    pb_size_t imu_features_count;
    float imu_features[6];
    pb_size_t flex_features_count;
    float flex_features[5];
    uint32_t l1_gesture_id;
} GloveData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GloveData_init_default                   {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0}
#define GloveData_init_zero                      {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GloveData_timestamp_tag                  1
#define GloveData_hall_features_tag              2
#define GloveData_imu_features_tag               3
#define GloveData_flex_features_tag              4
#define GloveData_l1_gesture_id_tag              5

/* Struct field encoding specification for nanopb */
extern const pb_msgDesc_t GloveData_msg;

/* Maximum encoded size of messages (where known) */
#define GloveData_size                           141

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
