/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "glove_data.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current nanopb-generator.
#endif

PB_BIND(GloveData, GloveData, 1)
