#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// Placeholder for the INT8 quantized TFLite model
// Generated by: xxd -i model_quant.tflite > model_data.h
const unsigned char g_model[] = {
  0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33, 0x00, 0x00, 0x12, 0x00,
  // ... (rest of the model data)
};
const int g_model_len = 38000; // ~38KB

#endif
